/**
 * Mock Character Data for Debug Mode
 */

import type { Character } from '@/types/character';

export const mockCharacter: Character = {
  id: 'debug-character-001',
  name: 'Aldric the Bold',
  playerName: 'Player One',
  race: {
    key: 'human',
    name: 'Human',
  },
  classes: [
    {
      key: 'fighter',
      name: 'Fighter',
      level: 5,
      hitDiceValue: 10,
      isPrimary: true,
    },
  ],
  background: {
    key: 'soldier',
    name: 'Soldier',
  },
  alignment: 'Lawful Good',
  level: 5,
  experiencePoints: 6500,
  edition: '2014',
  abilityScores: {
    base: { STR: 16, DEX: 14, CON: 15, INT: 10, WIS: 12, CHA: 8 },
    racialBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    asiBonus: { STR: 2, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    otherBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    override: { STR: null, DEX: null, CON: null, INT: null, WIS: null, CHA: null },
    total: { STR: 18, DEX: 14, CON: 15, INT: 10, WIS: 12, CHA: 8 },
    modifier: { STR: 4, DEX: 2, CON: 2, INT: 0, WIS: 1, CHA: -1 },
    generationMethod: 'standard',
  },
  skills: [
    { skillKey: 'athletics', proficiency: 'proficient', bonus: 7, source: 'Class: Fighter' },
    { skillKey: 'acrobatics', proficiency: 'none', bonus: 2, source: '' },
    { skillKey: 'perception', proficiency: 'proficient', bonus: 4, source: 'Background: Soldier' },
    { skillKey: 'intimidation', proficiency: 'proficient', bonus: 2, source: 'Class: Fighter' },
    { skillKey: 'survival', proficiency: 'proficient', bonus: 4, source: 'Background: Soldier' },
  ],
  combat: {
    maxHp: 49,
    currentHp: 42,
    tempHp: 5,
    ac: {
      base: 16,
      dexModifier: 2,
      bonus: 0,
      total: 18,
    },
    initiative: 2,
    speed: 30,
    hitDice: {
      type: 'd10',
      total: 5,
      used: 1,
    },
    deathSaves: {
      successes: 0,
      failures: 0,
    },
  },
  proficiencies: {
    armor: ['light', 'medium', 'heavy', 'shields'],
    weapons: ['simple', 'martial'],
    tools: [],
    languages: ['Common', 'Dwarvish'],
  },
  spellcasting: null,
  inventory: [],
  currency: {
    cp: 50,
    sp: 25,
    ep: 0,
    gp: 125,
    pp: 0,
  },
  features: [
    {
      id: 'fighting-style-defense',
      name: 'Fighting Style: Defense',
      description: 'While you are wearing armor, you gain a +1 bonus to AC.',
      source: 'Class: Fighter',
      level: 1,
    },
    {
      id: 'second-wind',
      name: 'Second Wind',
      description:
        'You can use a bonus action to regain hit points equal to 1d10 + your fighter level.',
      source: 'Class: Fighter',
      level: 1,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
    },
    {
      id: 'action-surge',
      name: 'Action Surge',
      description: 'You can take one additional action on your turn.',
      source: 'Class: Fighter',
      level: 2,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
    },
    {
      id: 'extra-attack',
      name: 'Extra Attack',
      description: 'You can attack twice, instead of once, whenever you take the Attack action.',
      source: 'Class: Fighter',
      level: 5,
    },
  ],
  conditions: [],
  personality: {
    traits: ['I am always polite and respectful.'],
    ideals: ['Respect. Respect is due to all.'],
    bonds: ['I fight for those who cannot fight for themselves.'],
    flaws: ['I have little respect for those who are not warriors.'],
    appearance: '',
    backstory: 'Aldric served in the royal army for years...',
    allies: '',
    enemies: '',
    notes: '',
  },
  appearance: {
    age: '28',
    height: '6\'2"',
    weight: '210 lbs',
    eyes: 'Blue',
    skin: 'Fair',
    hair: 'Blonde',
    other: '',
  },
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date(),
  campaignId: undefined,
  overrides: {},
};

export const mockSpellcaster: Character = {
  ...mockCharacter,
  id: 'debug-wizard-001',
  name: 'Elara Moonwhisper',
  classes: [
    {
      key: 'wizard',
      name: 'Wizard',
      level: 5,
      hitDiceValue: 6,
      isPrimary: true,
    },
  ],
  abilityScores: {
    base: { STR: 8, DEX: 14, CON: 13, INT: 16, WIS: 12, CHA: 10 },
    racialBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    asiBonus: { STR: 0, DEX: 0, CON: 0, INT: 2, WIS: 0, CHA: 0 },
    otherBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    override: { STR: null, DEX: null, CON: null, INT: null, WIS: null, CHA: null },
    total: { STR: 8, DEX: 14, CON: 13, INT: 18, WIS: 12, CHA: 10 },
    modifier: { STR: -1, DEX: 2, CON: 1, INT: 4, WIS: 1, CHA: 0 },
    generationMethod: 'standard',
  },
  combat: {
    maxHp: 32,
    currentHp: 28,
    tempHp: 0,
    ac: {
      base: 12,
      dexModifier: 2,
      bonus: 0,
      total: 14,
    },
    initiative: 2,
    speed: 30,
    hitDice: {
      type: 'd6',
      total: 5,
      used: 0,
    },
    deathSaves: {
      successes: 0,
      failures: 0,
    },
  },
  spellcasting: {
    ability: 'INT',
    saveDC: 15,
    attackBonus: 7,
    slots: [
      { level: 0, max: 0, used: 0 },
      { level: 1, max: 4, used: 1 },
      { level: 2, max: 3, used: 1 },
      { level: 3, max: 2, used: 0 },
    ],
    preparedSpells: [
      { spellKey: 'magic-missile', level: 1 },
      { spellKey: 'shield', level: 1 },
      { spellKey: 'scorching-ray', level: 2 },
    ],
    knownSpells: [
      {
        id: 'spell-1',
        spellKey: 'magic-missile',
        name: 'Magic Missile',
        level: 1,
        school: 'Evocation',
        prepared: true,
      },
      {
        id: 'spell-2',
        spellKey: 'shield',
        name: 'Shield',
        level: 1,
        school: 'Abjuration',
        prepared: true,
      },
      {
        id: 'spell-3',
        spellKey: 'mage-armor',
        name: 'Mage Armor',
        level: 1,
        school: 'Abjuration',
        prepared: false,
      },
      {
        id: 'spell-4',
        spellKey: 'burning-hands',
        name: 'Burning Hands',
        level: 1,
        school: 'Evocation',
        prepared: false,
      },
      {
        id: 'spell-5',
        spellKey: 'scorching-ray',
        name: 'Scorching Ray',
        level: 2,
        school: 'Evocation',
        prepared: true,
      },
      {
        id: 'spell-6',
        spellKey: 'misty-step',
        name: 'Misty Step',
        level: 2,
        school: 'Conjuration',
        prepared: false,
      },
      {
        id: 'spell-7',
        spellKey: 'fireball',
        name: 'Fireball',
        level: 3,
        school: 'Evocation',
        prepared: false,
      },
    ],
  },
  features: [
    {
      id: 'arcane-recovery',
      name: 'Arcane Recovery',
      description: 'Once per day, recover spell slots up to half your wizard level.',
      source: 'Class: Wizard',
      level: 1,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'long',
      },
    },
    {
      id: 'spellcasting-wizard',
      name: 'Spellcasting',
      description: 'You can cast wizard spells.',
      source: 'Class: Wizard',
      level: 1,
    },
  ],
};
