/**
 * Mock Character Data for Debug Mode
 */

import type { Character } from '@/types/character';

export const mockCharacter: Character = {
  id: 'debug-character-001',
  name: 'Aldric the Bold',
  playerName: 'Player One',
  race: {
    key: 'human',
    name: 'Human',
  },
  classes: [
    {
      key: 'fighter',
      name: 'Fighter',
      level: 5,
      hitDiceValue: 10,
      isPrimary: true,
    },
  ],
  background: {
    key: 'soldier',
    name: 'Soldier',
  },
  alignment: 'Lawful Good',
  level: 5,
  experiencePoints: 6500,
  edition: '2014',
  abilityScores: {
    base: { STR: 16, DEX: 14, CON: 15, INT: 10, WIS: 12, CHA: 8 },
    racialBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    asiBonus: { STR: 2, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    otherBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    override: { STR: null, DEX: null, CON: null, INT: null, WIS: null, CHA: null },
    total: { STR: 18, DEX: 14, CON: 15, INT: 10, WIS: 12, CHA: 8 },
    modifier: { STR: 4, DEX: 2, CON: 2, INT: 0, WIS: 1, CHA: -1 },
    generationMethod: 'standard',
  },
  skills: [
    { skillKey: 'athletics', proficiency: 'proficient', bonus: 7, source: 'Class: Fighter' },
    { skillKey: 'acrobatics', proficiency: 'none', bonus: 2, source: '' },
    { skillKey: 'perception', proficiency: 'proficient', bonus: 4, source: 'Background: Soldier' },
    { skillKey: 'intimidation', proficiency: 'proficient', bonus: 2, source: 'Class: Fighter' },
    { skillKey: 'survival', proficiency: 'proficient', bonus: 4, source: 'Background: Soldier' },
  ],
  combat: {
    maxHp: 49,
    currentHp: 42,
    tempHp: 5,
    ac: {
      base: 16,
      dexModifier: 2,
      bonus: 0,
      total: 18,
    },
    initiative: 2,
    speed: 30,
    hitDice: {
      type: 'd10',
      total: 5,
      used: 1,
    },
    deathSaves: {
      successes: 0,
      failures: 0,
    },
  },
  proficiencies: {
    armor: ['light', 'medium', 'heavy', 'shields'],
    weapons: ['simple', 'martial'],
    tools: [],
    languages: ['Common', 'Dwarvish'],
  },
  spellcasting: null,
  inventory: [
    {
      id: 'item-longsword',
      name: 'Longsword',
      quantity: 1,
      equipped: true,
      itemKey: 'longsword',
      // Extended fields for UI display
      description: 'A versatile longsword that can be used with one or two hands.',
      weight: '3 lb.',
      cost: '15 gp',
      category: 'Weapon',
      damageDice: '1d8',
      damageType: 'slashing',
      properties: ['Versatile (1d10)'],
    } as unknown as Character['inventory'][number],
    {
      id: 'item-chain-mail',
      name: 'Chain Mail',
      quantity: 1,
      equipped: true,
      itemKey: 'chain-mail',
      description:
        'Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath the mail.',
      weight: '55 lb.',
      cost: '75 gp',
      category: 'Armor',
      armorClass: 16,
      armorCategory: 'Heavy',
    } as unknown as Character['inventory'][number],
    {
      id: 'item-shield',
      name: 'Shield',
      quantity: 1,
      equipped: true,
      itemKey: 'shield',
      description: 'A shield is made from wood or metal and is carried in one hand.',
      weight: '6 lb.',
      cost: '10 gp',
      category: 'Armor',
      armorClass: 2,
      armorCategory: 'Shield',
    } as unknown as Character['inventory'][number],
    {
      id: 'item-explorer-pack',
      name: "Explorer's Pack",
      quantity: 1,
      equipped: false,
      description:
        'Includes a backpack, bedroll, mess kit, tinderbox, 10 torches, 10 days of rations, and waterskin.',
      weight: '59 lb.',
      category: 'Adventuring Gear',
    } as unknown as Character['inventory'][number],
    {
      id: 'item-health-potion',
      name: 'Potion of Healing',
      quantity: 2,
      equipped: false,
      itemKey: 'potion-of-healing',
      description: 'A character who drinks the magical red fluid regains 2d4 + 2 hit points.',
      category: 'Potion',
      isMagicItem: true,
    } as unknown as Character['inventory'][number],
    {
      id: 'item-rations',
      name: 'Rations (1 day)',
      quantity: 10,
      equipped: false,
      description: 'Dry foods suitable for extended travel.',
      weight: '2 lb.',
      cost: '5 sp',
      category: 'Adventuring Gear',
    } as unknown as Character['inventory'][number],
  ],
  currency: {
    cp: 50,
    sp: 25,
    ep: 0,
    gp: 125,
    pp: 0,
  },
  features: [
    // Class Features
    {
      id: 'fighting-style-defense',
      name: 'Fighting Style: Defense',
      description: 'While you are wearing armor, you gain a +1 bonus to AC.',
      source: 'Class: Fighter',
      level: 1,
    },
    {
      id: 'second-wind',
      name: 'Second Wind',
      description:
        'You have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use a bonus action to regain hit points equal to 1d10 + your fighter level. Once you use this feature, you must finish a short or long rest before you can use it again.',
      source: 'Class: Fighter',
      level: 1,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
    },
    {
      id: 'action-surge',
      name: 'Action Surge',
      description:
        'Starting at 2nd level, you can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action on top of your regular action and possible bonus action. Once you use this feature, you must finish a short or long rest before you can use it again.',
      source: 'Class: Fighter',
      level: 2,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
    },
    {
      id: 'extra-attack',
      name: 'Extra Attack',
      description:
        'Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.',
      source: 'Class: Fighter',
      level: 5,
    },
    // Species Traits
    {
      id: 'human-versatility',
      name: 'Human Versatility',
      description:
        'Humans are the most adaptable and ambitious people among the common races. They have widely varying tastes, morals, and customs in the many different lands where they have settled. When they settle, though, they stay: they build cities to last for the ages.',
      source: 'Species: Human',
    },
    {
      id: 'human-ability-increase',
      name: 'Ability Score Increase',
      description: 'Your ability scores each increase by 1.',
      source: 'Species: Human',
    },
    // Background Feature
    {
      id: 'soldier-military-rank',
      name: 'Military Rank',
      description:
        'You have a military rank from your career as a soldier. Soldiers loyal to your former military organization still recognize your authority and influence, and they defer to you if they are of a lower rank. You can invoke your rank to exert influence over other soldiers and requisition simple equipment or horses for temporary use. You can also usually gain access to friendly military encampments and fortresses where your rank is recognized.',
      source: 'Background: Soldier',
    },
    // Feat
    {
      id: 'feat-sentinel',
      name: 'Sentinel',
      description:
        "You have mastered techniques to take advantage of every drop in any enemy's guard. When you hit a creature with an opportunity attack, the creature's speed becomes 0 for the rest of the turn. Creatures provoke opportunity attacks from you even if they take the Disengage action before leaving your reach. When a creature within 5 feet of you makes an attack against a target other than you (and that target doesn't have this feat), you can use your reaction to make a melee weapon attack against the attacking creature.",
      source: 'Feat: Sentinel',
    },
  ],
  actions: [
    {
      id: 'longsword-attack',
      name: 'Longsword',
      type: 'action',
      description: 'A versatile longsword, can be used with one or two hands.',
      isAttack: true,
      attackDetails: {
        id: 'longsword-attack-details',
        name: 'Longsword',
        ability: 'STR',
        bonus: 7, // +4 STR + +3 proficiency
        damage: '1d8+4',
        damageType: 'slashing',
        range: '5 ft.',
        properties: ['Versatile (1d10)'],
      },
      source: 'weapon',
      sourceKey: 'longsword',
    },
    {
      id: 'handaxe-attack',
      name: 'Handaxe',
      type: 'action',
      description: 'A light thrown weapon, good for ranged attacks.',
      isAttack: true,
      attackDetails: {
        id: 'handaxe-attack-details',
        name: 'Handaxe',
        ability: 'STR',
        bonus: 7,
        damage: '1d6+4',
        damageType: 'slashing',
        range: '20/60 ft.',
        properties: ['Light', 'Thrown'],
      },
      source: 'weapon',
      sourceKey: 'handaxe',
    },
    {
      id: 'second-wind-action',
      name: 'Second Wind',
      type: 'bonus',
      description:
        'You have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use a bonus action to regain hit points equal to 1d10 + your fighter level.',
      isAttack: false,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
      source: 'feature',
      sourceKey: 'second-wind',
    },
    {
      id: 'action-surge-action',
      name: 'Action Surge',
      type: 'action',
      description:
        'Starting at 2nd level, you can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action. Once you use this feature, you must finish a short or long rest before you can use it again.',
      isAttack: false,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
      source: 'feature',
      sourceKey: 'action-surge',
    },
    {
      id: 'opportunity-attack',
      name: 'Opportunity Attack',
      type: 'reaction',
      description:
        'You can make an opportunity attack when a hostile creature that you can see moves out of your reach. To make the opportunity attack, you use your reaction to make one melee attack against the provoking creature.',
      isAttack: true,
      attackDetails: {
        id: 'opportunity-attack-details',
        name: 'Opportunity Attack',
        ability: 'STR',
        bonus: 7,
        damage: '1d8+4',
        damageType: 'slashing',
        range: '5 ft.',
        properties: [],
      },
      source: 'feature',
      sourceKey: 'opportunity-attack',
    },
  ],
  conditions: [],
  personality: {
    traits: ['I am always polite and respectful.'],
    ideals: ['Respect. Respect is due to all.'],
    bonds: ['I fight for those who cannot fight for themselves.'],
    flaws: ['I have little respect for those who are not warriors.'],
    appearance: '',
    backstory: 'Aldric served in the royal army for years...',
    allies: '',
    enemies: '',
    notes: '',
  },
  appearance: {
    age: '28',
    height: '6\'2"',
    weight: '210 lbs',
    eyes: 'Blue',
    skin: 'Fair',
    hair: 'Blonde',
    other: '',
  },
  sessionNotes: [],
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date(),
  campaignId: undefined,
  overrides: {},
};

export const mockSpellcaster: Character = {
  ...mockCharacter,
  id: 'debug-wizard-001',
  name: 'Elara Moonwhisper',
  classes: [
    {
      key: 'wizard',
      name: 'Wizard',
      level: 5,
      hitDiceValue: 6,
      isPrimary: true,
    },
  ],
  abilityScores: {
    base: { STR: 8, DEX: 14, CON: 13, INT: 16, WIS: 12, CHA: 10 },
    racialBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    asiBonus: { STR: 0, DEX: 0, CON: 0, INT: 2, WIS: 0, CHA: 0 },
    otherBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    override: { STR: null, DEX: null, CON: null, INT: null, WIS: null, CHA: null },
    total: { STR: 8, DEX: 14, CON: 13, INT: 18, WIS: 12, CHA: 10 },
    modifier: { STR: -1, DEX: 2, CON: 1, INT: 4, WIS: 1, CHA: 0 },
    generationMethod: 'standard',
  },
  combat: {
    maxHp: 32,
    currentHp: 28,
    tempHp: 0,
    ac: {
      base: 12,
      dexModifier: 2,
      bonus: 0,
      total: 14,
    },
    initiative: 2,
    speed: 30,
    hitDice: {
      type: 'd6',
      total: 5,
      used: 0,
    },
    deathSaves: {
      successes: 0,
      failures: 0,
    },
  },
  spellcasting: {
    ability: 'INT',
    saveDC: 15,
    attackBonus: 7,
    slots: [
      { level: 0, max: 0, used: 0 },
      { level: 1, max: 4, used: 1 },
      { level: 2, max: 3, used: 1 },
      { level: 3, max: 2, used: 0 },
    ],
    preparedSpells: [
      { spellKey: 'magic-missile', level: 1 },
      { spellKey: 'shield', level: 1 },
      { spellKey: 'scorching-ray', level: 2 },
    ],
    knownSpells: [
      {
        id: 'spell-1',
        spellKey: 'magic-missile',
        name: 'Magic Missile',
        level: 1,
        school: 'Evocation',
        prepared: true,
      },
      {
        id: 'spell-2',
        spellKey: 'shield',
        name: 'Shield',
        level: 1,
        school: 'Abjuration',
        prepared: true,
      },
      {
        id: 'spell-3',
        spellKey: 'mage-armor',
        name: 'Mage Armor',
        level: 1,
        school: 'Abjuration',
        prepared: false,
      },
      {
        id: 'spell-4',
        spellKey: 'burning-hands',
        name: 'Burning Hands',
        level: 1,
        school: 'Evocation',
        prepared: false,
      },
      {
        id: 'spell-5',
        spellKey: 'scorching-ray',
        name: 'Scorching Ray',
        level: 2,
        school: 'Evocation',
        prepared: true,
      },
      {
        id: 'spell-6',
        spellKey: 'misty-step',
        name: 'Misty Step',
        level: 2,
        school: 'Conjuration',
        prepared: false,
      },
      {
        id: 'spell-7',
        spellKey: 'fireball',
        name: 'Fireball',
        level: 3,
        school: 'Evocation',
        prepared: false,
      },
    ],
  },
  features: [
    // Class Features
    {
      id: 'arcane-recovery',
      name: 'Arcane Recovery',
      description:
        'You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher.',
      source: 'Class: Wizard',
      level: 1,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'long',
      },
    },
    {
      id: 'spellcasting-wizard',
      name: 'Spellcasting',
      description:
        'As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power. Your spellbook is the repository of the wizard spells you know. It starts with 6 first-level wizard spells of your choice.',
      source: 'Class: Wizard',
      level: 1,
    },
    // Species Traits
    {
      id: 'human-versatility',
      name: 'Human Versatility',
      description:
        'Humans are the most adaptable and ambitious people among the common races. They have widely varying tastes, morals, and customs in the many different lands where they have settled.',
      source: 'Species: Human',
    },
    {
      id: 'human-ability-increase',
      name: 'Ability Score Increase',
      description: 'Your ability scores each increase by 1.',
      source: 'Species: Human',
    },
    // Background Feature
    {
      id: 'sage-researcher',
      name: 'Researcher',
      description:
        'When you attempt to learn or recall a piece of lore, if you do not know that information, you often know where and from whom you can obtain it. Usually, this information comes from a library, scriptorium, university, or a sage or other learned person or creature. Your DM might rule that the knowledge you seek is secreted away in an almost inaccessible place, or that it simply cannot be found. Unearthing the deepest secrets of the multiverse can require an adventure or even a whole campaign.',
      source: 'Background: Sage',
    },
    // Feat
    {
      id: 'feat-war-caster',
      name: 'War Caster',
      description:
        "You have practiced casting spells in the midst of combat, learning techniques that grant you the following benefits: You have advantage on Constitution saving throws that you make to maintain your concentration on a spell when you take damage. You can perform the somatic components of spells even when you have weapons or a shield in one or both hands. When a hostile creature's movement provokes an opportunity attack from you, you can use your reaction to cast a spell at the creature, rather than making an opportunity attack. The spell must have a casting time of 1 action and must target only that creature.",
      source: 'Feat: War Caster',
    },
  ],
  actions: [
    {
      id: 'dagger-attack',
      name: 'Dagger',
      type: 'action',
      description: 'A simple dagger for close combat.',
      isAttack: true,
      attackDetails: {
        id: 'dagger-attack-details',
        name: 'Dagger',
        ability: 'DEX',
        bonus: 5, // +2 DEX + +3 proficiency
        damage: '1d4+2',
        damageType: 'piercing',
        range: '20/60 ft.',
        properties: ['Finesse', 'Light', 'Thrown'],
      },
      source: 'weapon',
      sourceKey: 'dagger',
    },
    {
      id: 'fire-bolt-cantrip',
      name: 'Fire Bolt',
      type: 'action',
      description: 'You hurl a mote of fire at a creature or object within range.',
      isAttack: true,
      attackDetails: {
        id: 'fire-bolt-attack-details',
        name: 'Fire Bolt',
        ability: 'INT',
        bonus: 7, // +4 INT + +3 proficiency
        damage: '2d10',
        damageType: 'fire',
        range: '120 ft.',
        properties: ['Cantrip'],
      },
      source: 'spell',
      sourceKey: 'fire-bolt',
    },
    {
      id: 'shield-spell',
      name: 'Shield',
      type: 'reaction',
      description:
        'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack.',
      isAttack: false,
      source: 'spell',
      sourceKey: 'shield',
    },
  ],
  conditions: [],
  personality: {
    traits: ['I use polysyllabic words that convey the impression of great erudition.'],
    ideals: ['Knowledge. The path to power and self-improvement is through knowledge.'],
    bonds: ['I have an ancient text that holds terrible secrets.'],
    flaws: ['I am easily distracted by the promise of information.'],
    appearance: '',
    backstory: 'Elara grew up in a library...',
    allies: '',
    enemies: '',
    notes: '',
  },
  appearance: {
    age: '24',
    height: '5\'6"',
    weight: '120 lbs',
    eyes: 'Hazel',
    skin: 'Olive',
    hair: 'Brown',
    other: '',
  },
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date(),
  overrides: {},
};
