/**
 * Mock Character Data for Debug Mode
 */

import type { Character } from '@/types/character';

export const mockCharacter: Character = {
  id: 'debug-character-001',
  name: 'Aldric the Bold',
  playerName: 'Player One',
  race: {
    key: 'human',
    name: 'Human',
  },
  classes: [
    {
      key: 'fighter',
      name: 'Fighter',
      level: 5,
      hitDiceValue: 10,
      isPrimary: true,
    },
  ],
  background: {
    key: 'soldier',
    name: 'Soldier',
  },
  alignment: 'Lawful Good',
  level: 5,
  experiencePoints: 6500,
  edition: '2014',
  abilityScores: {
    base: { STR: 16, DEX: 14, CON: 15, INT: 10, WIS: 12, CHA: 8 },
    racialBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    asiBonus: { STR: 2, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    otherBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    override: { STR: null, DEX: null, CON: null, INT: null, WIS: null, CHA: null },
    total: { STR: 18, DEX: 14, CON: 15, INT: 10, WIS: 12, CHA: 8 },
    modifier: { STR: 4, DEX: 2, CON: 2, INT: 0, WIS: 1, CHA: -1 },
    generationMethod: 'standard',
  },
  skills: [
    { skillKey: 'athletics', proficiency: 'proficient', bonus: 7, source: 'Class: Fighter' },
    { skillKey: 'acrobatics', proficiency: 'none', bonus: 2, source: '' },
    { skillKey: 'perception', proficiency: 'proficient', bonus: 4, source: 'Background: Soldier' },
    { skillKey: 'intimidation', proficiency: 'proficient', bonus: 2, source: 'Class: Fighter' },
    { skillKey: 'survival', proficiency: 'proficient', bonus: 4, source: 'Background: Soldier' },
  ],
  combat: {
    maxHp: 49,
    currentHp: 42,
    tempHp: 5,
    ac: {
      base: 16,
      dexModifier: 2,
      bonus: 0,
      total: 18,
    },
    initiative: 2,
    speed: 30,
    hitDice: {
      type: 'd10',
      total: 5,
      used: 1,
    },
    deathSaves: {
      successes: 0,
      failures: 0,
    },
  },
  proficiencies: {
    armor: ['light', 'medium', 'heavy', 'shields'],
    weapons: ['simple', 'martial'],
    tools: [],
    languages: ['Common', 'Dwarvish'],
  },
  spellcasting: null,
  inventory: [],
  currency: {
    cp: 50,
    sp: 25,
    ep: 0,
    gp: 125,
    pp: 0,
  },
  features: [
    {
      id: 'fighting-style-defense',
      name: 'Fighting Style: Defense',
      description: 'While you are wearing armor, you gain a +1 bonus to AC.',
      source: 'Class: Fighter',
      level: 1,
    },
    {
      id: 'second-wind',
      name: 'Second Wind',
      description:
        'You can use a bonus action to regain hit points equal to 1d10 + your fighter level.',
      source: 'Class: Fighter',
      level: 1,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
    },
    {
      id: 'action-surge',
      name: 'Action Surge',
      description: 'You can take one additional action on your turn.',
      source: 'Class: Fighter',
      level: 2,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
    },
    {
      id: 'extra-attack',
      name: 'Extra Attack',
      description: 'You can attack twice, instead of once, whenever you take the Attack action.',
      source: 'Class: Fighter',
      level: 5,
    },
  ],
  actions: [
    {
      id: 'longsword-attack',
      name: 'Longsword',
      type: 'action',
      description: 'A versatile longsword, can be used with one or two hands.',
      isAttack: true,
      attackDetails: {
        id: 'longsword-attack-details',
        name: 'Longsword',
        ability: 'STR',
        bonus: 7, // +4 STR + +3 proficiency
        damage: '1d8+4',
        damageType: 'slashing',
        range: '5 ft.',
        properties: ['Versatile (1d10)'],
      },
      source: 'weapon',
      sourceKey: 'longsword',
    },
    {
      id: 'handaxe-attack',
      name: 'Handaxe',
      type: 'action',
      description: 'A light thrown weapon, good for ranged attacks.',
      isAttack: true,
      attackDetails: {
        id: 'handaxe-attack-details',
        name: 'Handaxe',
        ability: 'STR',
        bonus: 7,
        damage: '1d6+4',
        damageType: 'slashing',
        range: '20/60 ft.',
        properties: ['Light', 'Thrown'],
      },
      source: 'weapon',
      sourceKey: 'handaxe',
    },
    {
      id: 'second-wind-action',
      name: 'Second Wind',
      type: 'bonus',
      description:
        'You have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use a bonus action to regain hit points equal to 1d10 + your fighter level.',
      isAttack: false,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
      source: 'feature',
      sourceKey: 'second-wind',
    },
    {
      id: 'action-surge-action',
      name: 'Action Surge',
      type: 'action',
      description:
        'Starting at 2nd level, you can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action. Once you use this feature, you must finish a short or long rest before you can use it again.',
      isAttack: false,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'short',
      },
      source: 'feature',
      sourceKey: 'action-surge',
    },
    {
      id: 'opportunity-attack',
      name: 'Opportunity Attack',
      type: 'reaction',
      description:
        'You can make an opportunity attack when a hostile creature that you can see moves out of your reach. To make the opportunity attack, you use your reaction to make one melee attack against the provoking creature.',
      isAttack: true,
      attackDetails: {
        id: 'opportunity-attack-details',
        name: 'Opportunity Attack',
        ability: 'STR',
        bonus: 7,
        damage: '1d8+4',
        damageType: 'slashing',
        range: '5 ft.',
        properties: [],
      },
      source: 'feature',
      sourceKey: 'opportunity-attack',
    },
  ],
  conditions: [],
  personality: {
    traits: ['I am always polite and respectful.'],
    ideals: ['Respect. Respect is due to all.'],
    bonds: ['I fight for those who cannot fight for themselves.'],
    flaws: ['I have little respect for those who are not warriors.'],
    appearance: '',
    backstory: 'Aldric served in the royal army for years...',
    allies: '',
    enemies: '',
    notes: '',
  },
  appearance: {
    age: '28',
    height: '6\'2"',
    weight: '210 lbs',
    eyes: 'Blue',
    skin: 'Fair',
    hair: 'Blonde',
    other: '',
  },
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date(),
  campaignId: undefined,
  overrides: {},
};

export const mockSpellcaster: Character = {
  ...mockCharacter,
  id: 'debug-wizard-001',
  name: 'Elara Moonwhisper',
  classes: [
    {
      key: 'wizard',
      name: 'Wizard',
      level: 5,
      hitDiceValue: 6,
      isPrimary: true,
    },
  ],
  abilityScores: {
    base: { STR: 8, DEX: 14, CON: 13, INT: 16, WIS: 12, CHA: 10 },
    racialBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    asiBonus: { STR: 0, DEX: 0, CON: 0, INT: 2, WIS: 0, CHA: 0 },
    otherBonus: { STR: 0, DEX: 0, CON: 0, INT: 0, WIS: 0, CHA: 0 },
    override: { STR: null, DEX: null, CON: null, INT: null, WIS: null, CHA: null },
    total: { STR: 8, DEX: 14, CON: 13, INT: 18, WIS: 12, CHA: 10 },
    modifier: { STR: -1, DEX: 2, CON: 1, INT: 4, WIS: 1, CHA: 0 },
    generationMethod: 'standard',
  },
  combat: {
    maxHp: 32,
    currentHp: 28,
    tempHp: 0,
    ac: {
      base: 12,
      dexModifier: 2,
      bonus: 0,
      total: 14,
    },
    initiative: 2,
    speed: 30,
    hitDice: {
      type: 'd6',
      total: 5,
      used: 0,
    },
    deathSaves: {
      successes: 0,
      failures: 0,
    },
  },
  spellcasting: {
    ability: 'INT',
    saveDC: 15,
    attackBonus: 7,
    slots: [
      { level: 0, max: 0, used: 0 },
      { level: 1, max: 4, used: 1 },
      { level: 2, max: 3, used: 1 },
      { level: 3, max: 2, used: 0 },
    ],
    preparedSpells: [
      { spellKey: 'magic-missile', level: 1 },
      { spellKey: 'shield', level: 1 },
      { spellKey: 'scorching-ray', level: 2 },
    ],
    knownSpells: [
      {
        id: 'spell-1',
        spellKey: 'magic-missile',
        name: 'Magic Missile',
        level: 1,
        school: 'Evocation',
        prepared: true,
      },
      {
        id: 'spell-2',
        spellKey: 'shield',
        name: 'Shield',
        level: 1,
        school: 'Abjuration',
        prepared: true,
      },
      {
        id: 'spell-3',
        spellKey: 'mage-armor',
        name: 'Mage Armor',
        level: 1,
        school: 'Abjuration',
        prepared: false,
      },
      {
        id: 'spell-4',
        spellKey: 'burning-hands',
        name: 'Burning Hands',
        level: 1,
        school: 'Evocation',
        prepared: false,
      },
      {
        id: 'spell-5',
        spellKey: 'scorching-ray',
        name: 'Scorching Ray',
        level: 2,
        school: 'Evocation',
        prepared: true,
      },
      {
        id: 'spell-6',
        spellKey: 'misty-step',
        name: 'Misty Step',
        level: 2,
        school: 'Conjuration',
        prepared: false,
      },
      {
        id: 'spell-7',
        spellKey: 'fireball',
        name: 'Fireball',
        level: 3,
        school: 'Evocation',
        prepared: false,
      },
    ],
  },
  features: [
    {
      id: 'arcane-recovery',
      name: 'Arcane Recovery',
      description: 'Once per day, recover spell slots up to half your wizard level.',
      source: 'Class: Wizard',
      level: 1,
      uses: {
        max: 1,
        used: 0,
        resetOn: 'long',
      },
    },
    {
      id: 'spellcasting-wizard',
      name: 'Spellcasting',
      description: 'You can cast wizard spells.',
      source: 'Class: Wizard',
      level: 1,
    },
  ],
  actions: [
    {
      id: 'dagger-attack',
      name: 'Dagger',
      type: 'action',
      description: 'A simple dagger for close combat.',
      isAttack: true,
      attackDetails: {
        id: 'dagger-attack-details',
        name: 'Dagger',
        ability: 'DEX',
        bonus: 5, // +2 DEX + +3 proficiency
        damage: '1d4+2',
        damageType: 'piercing',
        range: '20/60 ft.',
        properties: ['Finesse', 'Light', 'Thrown'],
      },
      source: 'weapon',
      sourceKey: 'dagger',
    },
    {
      id: 'fire-bolt-cantrip',
      name: 'Fire Bolt',
      type: 'action',
      description: 'You hurl a mote of fire at a creature or object within range.',
      isAttack: true,
      attackDetails: {
        id: 'fire-bolt-attack-details',
        name: 'Fire Bolt',
        ability: 'INT',
        bonus: 7, // +4 INT + +3 proficiency
        damage: '2d10',
        damageType: 'fire',
        range: '120 ft.',
        properties: ['Cantrip'],
      },
      source: 'spell',
      sourceKey: 'fire-bolt',
    },
    {
      id: 'shield-spell',
      name: 'Shield',
      type: 'reaction',
      description:
        'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack.',
      isAttack: false,
      source: 'spell',
      sourceKey: 'shield',
    },
  ],
  conditions: [],
  personality: {
    traits: ['I use polysyllabic words that convey the impression of great erudition.'],
    ideals: ['Knowledge. The path to power and self-improvement is through knowledge.'],
    bonds: ['I have an ancient text that holds terrible secrets.'],
    flaws: ['I am easily distracted by the promise of information.'],
    appearance: '',
    backstory: 'Elara grew up in a library...',
    allies: '',
    enemies: '',
    notes: '',
  },
  appearance: {
    age: '24',
    height: '5\'6"',
    weight: '120 lbs',
    eyes: 'Hazel',
    skin: 'Olive',
    hair: 'Brown',
    other: '',
  },
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date(),
  overrides: {},
};
